//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentum
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class documentumEntities : DbContext
    {
        public documentumEntities()
            : base("name=documentumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bookmark> Bookmarks { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<DokumentTip> DokumentTips { get; set; }
        public virtual DbSet<Grupa> Grupas { get; set; }
        public virtual DbSet<Nastavnik> Nastavniks { get; set; }
        public virtual DbSet<Predmet> Predmets { get; set; }
        public virtual DbSet<Razred> Razreds { get; set; }
        public virtual DbSet<Smer> Smers { get; set; }
        public virtual DbSet<SmerGodina> SmerGodinas { get; set; }
        public virtual DbSet<SmerGodinaDokument> SmerGodinaDokuments { get; set; }
        public virtual DbSet<SmerGodinaPredmet> SmerGodinaPredmets { get; set; }
        public virtual DbSet<Ucenik> Uceniks { get; set; }
        public virtual DbSet<UcenikDokument> UcenikDokuments { get; set; }
        public virtual DbSet<UcenikGrupa> UcenikGrupas { get; set; }
        public virtual DbSet<UcenikOcena> UcenikOcenas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
