//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentum
{
    using System;
    using System.Collections.Generic;
    
    public partial class DokumentTip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DokumentTip()
        {
            this.Bookmarks = new HashSet<Bookmark>();
            this.SmerGodinaDokuments = new HashSet<SmerGodinaDokument>();
            this.UcenikDokuments = new HashSet<UcenikDokument>();
        }
    
        public int Id { get; set; }
        public string naziv { get; set; }
        public string templatePath { get; set; }
        public string dataSP { get; set; }
        public string outputPath { get; set; }
        public string previewTemplatePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmerGodinaDokument> SmerGodinaDokuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcenikDokument> UcenikDokuments { get; set; }
    }
}
