select +ACo- from nastavnik 
go
insert into Nastavnik (prezime, ime) select '+BAsEQwRABDQEOARb-', '+BAgENQQ7BDUEPQQw-             '
insert into Nastavnik (prezime, ime) select '+BAgEPgQyBDAEPQQ0BDgEWw-', '+BAgEMARBBDwEOAQ9BDoEMA-         '
insert into Nastavnik (prezime, ime) select '+BCAEOARBBEIEOARb-', '+BBEEOARBBDUEQAQ6BDA-            '
insert into Nastavnik (prezime, ime) select '+BB8ENQRIBDgEWw-', '+BBoEMARCBDAEQAQ4BD0EMA-            '
insert into Nastavnik (prezime, ime) select '+BBsENQQ6BDgEWw-', '+BBwEOARABDA-                '
insert into Nastavnik (prezime, ime) select '+BBYENQQxBDUEWQQwBD0-', '+BBMEPgRABDQEMAQ9BDA-           '
insert into Nastavnik (prezime, ime) select '+BBsEQwQ6BDgEWw-', '+BBAEPQQw-                 '
insert into Nastavnik (prezime, ime) select '+BCEEQgQwBD0EOARIBDgEWw-', '+BCEEQARSBDAEPQQw-           '
insert into Nastavnik (prezime, ime) select '+BB8EMAQyBDsEPgQyBDgEWw-', '+BAgENQQ7BDUEPQQw-           '
insert into Nastavnik (prezime, ime) select '+BCEEQgQwBD0ERwQ4BFs-', '+BBIEQwRHBDoEPgQyBDgEWw- +BBUEPAQ4BDsEOARYBDA-  '
insert into Nastavnik (prezime, ime) select '+BBQEOAQ8BDgEQgRABDgEWAQ1BDIEOARb-', '+BBwEMARABDgEWAQwBD0-      '
insert into Nastavnik (prezime, ime) select '+BAgENQQyBEAENQQ8BD4EMgQ4BFs-', '+BCMEQAQ+BEg-           '
insert into Nastavnik (prezime, ime) select 'Jo+BEcEOARb-', '+BBEEQAQwBD0EOgQw-              '
insert into Nastavnik (prezime, ime) select '+BBEEPgQ2BDgEWw-', '+BCEEOwQwBDIEOARGBDA-             '
insert into Nastavnik (prezime, ime) select '+BBQEQAQwBDMEPgQyBDgEWw-', '+BBQEQAQwBDMEMAQ9BDA-          '
insert into Nastavnik (prezime, ime) select '+BBwEMARCBD4EMgQ4BFs-', '+BCIEMAQ8BDAEQAQw-            '
insert into Nastavnik (prezime, ime) select '+BAgEMAQxBDsEMAQ9-', '+BBQEQAQwBDMEMAQ9BDA-            '
insert into Nastavnik (prezime, ime) select '+BBoEPgRBBEIEOARb-', '+BBcEPgRABDgERgQw-             '
insert into Nastavnik (prezime, ime) select '+BCMENwQ1BDsEMARG-', '+BBwEOARABDA-               '
insert into Nastavnik (prezime, ime) select '+BAgENQQyBEAENQQ8BD4EMgQ4BFs-', '+BCEEMARIBDoEMA-          '
insert into Nastavnik (prezime, ime) select '+BCEENQQ7BDUEPQQ4BFs-', '+BCEEMARaBDA-              '
insert into Nastavnik (prezime, ime) select '+BBYEOAQyBD4EWAQ4BD0EPgQyBDgEWw-', '+BAgENQQ7BDUEPQQw-        '
insert into Nastavnik (prezime, ime) select '+BBcENARABDAEMgQ6BD4EMgQ4BFs-', '+BCAEMAQ0BDwEOAQ7BDA-        '
insert into Nastavnik (prezime, ime) select '+BBMEQARDBFgEOARHBDgEWw-', '+BCEEQgQwBD0EOgQ+-           '
insert into Nastavnik (prezime, ime) select '+BBwEOARCBEAEPgQyBDgEWw-', '+BBIENQRBBD0EMA-            '
insert into Nastavnik (prezime, ime) select '+BCIEPgQ8BDA-', '+BBwEMARYBDA-                 '
insert into Nastavnik (prezime, ime) select '+BB8EPgQ/BD4EMgQ4BFs-', '+BBIEMAQ7BDUEPQRCBDgEPQQw-         '
insert into Nastavnik (prezime, ime) select '+BB8EMAQyBDgEWwQ1BDIEOARb-', '+BCIEMARCBFgEMAQ9BDA-         '
insert into Nastavnik (prezime, ime) select '+BCYEPgQ9BDgEWw-', '+BAgENQQ7BDUEPQQw-              '
insert into Nastavnik (prezime, ime) select '+BA8EMAQ9BDgEWw-', '+BBgEMwQ+BEA-                '
insert into Nastavnik (prezime, ime) select 'K+BD0ENQQ2BDUEMgQ4BFs-', '+BBwEMARABDgERgQw-           '
insert into Nastavnik (prezime, ime) select '+BCgEPgQxBDAEWAQ4BFs-', '+BBwEMARABDgEWAQw-            '
insert into Nastavnik (prezime, ime) select '+BAgEPgQyBDAEPQQ+BDIEOARb-', '+BCIEMAQ8BDAEQAQw-          '
insert into Nastavnik (prezime, ime) select '+BCAEMAQ9BDgEOwQ+BDIEOARb-', '+BBwEOAQ7BDUEPQQw-          '
insert into Nastavnik (prezime, ime) select '+BCcEQwQxBEAEOAQ7BD4-', '+BBMEPgRABDQEMAQ9BDA-           '
insert into Nastavnik (prezime, ime) select '+BCEEQgQwBD0EOgQ+BDIEOARb-', '+BBgEMgQwBD0-            '
insert into Nastavnik (prezime, ime) select '+BBIEOARCBDoEPgQyBDgEWw-', '+BCEEMgQ1BEIEOwQwBD0EMA-         '
insert into Nastavnik (prezime, ime) select '+BBoEQARBBEIEOARb-', '+BBQEQAQwBDMEOARGBDA-            '
insert into Nastavnik (prezime, ime) select '+BBwEMARABFgEMAQ9BD4EMgQ4BFs-', '+BBwEMARABDgEWAQw-         '
insert into Nastavnik (prezime, ime) select '+BBMEOwQ4BEgEOARb-', '+BCEEPgRaBDA-               '
go