insert into Predmet (naziv)
select distinct(rtrim(naziv)) from
(
select  rtrim(naziv) as naziv
from (
select '+BCEEQAQ/BEEEOgQ4- +BFgENQQ3BDgEOg- +BDg- +BDoEWgQ4BDYENQQyBD0EPgRBBEI-'       as naziv                         
union select '+BBUEPQQzBDsENQRBBDoEOA- +BFgENQQ3BDgEOg-'                                     
union select '+BBgEQQRCBD4EQAQ4BFgEMA-'                                           
union select '+BBwEQwQ3BDgERwQ6BDA- +BEMEPAQ1BEIEPQQ+BEEEQg-'                                   
union select '+BCQEOAQ3BDgERwQ6BD4- +BDIEMARBBD8EOARCBDAEWgQ1-'                                  
union select '+BBwEMARCBDUEPAQwBEIEOAQ6BDA-'                                         
union select '+BCAEMARHBEMEPQQwBEAEQQRCBDIEPg- +BDg- +BDgEPQREBD4EQAQ8BDAEQgQ4BDoEMA-'                          
union select '+BBMENQQ+BDMEQAQwBEQEOARYBDA-'                                         
union select '+BCQEOAQ3BDgEOgQw-'                                             
union select '+BCUENQQ8BDgEWAQw-'                                             
union select '+BBEEOAQ+BDsEPgQzBDgEWAQw-'                                          
union select '+BB4EQQQ9BD4EMgQ4- +BDUEOgQ+BD0EPgQ8BDgEOgQ1- +BEIEQAQzBD4EMgQ4BD0ENQ-'                          
union select '+BBAEQAQwBD0ENgQ4BEAEMARaBDU- +BEM- +BEIEQAQzBD4EMgQ4BD0EOA-'                              
union select '+BCYEQARCBDAEWgQ1- +BDg- +BD4EMQQ7BDgEOgQ+BDIEMARaBDU-'                                
union select '+BBIENQRABEEEOgQw- +BD0EMARBBEIEMAQyBDA-'                                     
union select '+BBMEQAQwBFIEMAQ9BEEEOgQ+- +BDIEMARBBD8EOARCBDAEWgQ1-'                                
union select '+BCEEQAQ/BEEEOgQ4- +BFgENQQ3BDgEOg- +BDg- +BDoEWgQ4BDYENQQyBD0EPgRBBEI-'	                         
union select '+BBUEPQQzBDsENQRBBDoEOA- +BFgENQQ3BDgEOg-' 	                                 
union select '+BBgEQQRCBD4EQAQ4BFgEMA-'	                                         
union select '+BBsEOAQ6BD4EMgQ9BDA- +BDoEQwQ7BEIEQwRABDA-'		                             
union select '+BCQEOAQ3BDgERwQ6BD4- +BDIEMARBBD8EOARCBDAEWgQ1-'		                             
union select '+BBwEMARCBDUEPAQwBEIEOAQ6BDA-'		                                 
union select '+BCQEOAQ3BDgEOgQw-'			                                 
union select '+BBUEOgQ+BD0EPgQ8BDgEOgQw- +BDg- +BD4EQAQzBDAEPQQ4BDcEMARGBDgEWAQw- +BEIEQAQzBD4EMgQ4BD0EQQQ6BDgERQ- +BD8EQAQ1BDQEQwQ3BDUEWwQw-'	
union select '+BBAEQAQwBD0ENgQ4BEAEMARaBDU- +BEM- +BEIEQAQzBD4EMgQ4BD0EOA-'		                         
union select '+BCYEQARCBDAEWgQ1- +BDg- +BD4EMQQ7BDgEOgQ+BDIEMARaBDU-'		                         
union select '+BB0EMARGBEAEQgQ9BDA- +BDMENQQ+BDwENQRCBEAEOARYBDA-'	                             
union select '+BCQEPgRABDwEMA- +BDg- +BD4EMQQ7BDgEOgQ+BDIEMARaBDU-'			                     
union select '+BB8EPgQ3BD0EMAQyBDAEWgQ1- +BDwEMARCBDUEQAQ4BFgEMAQ7BDA- +BDg- +BEAEPgQxBDU-'	                     
union select '+BBIENQRABEEEOgQw- +BD0EMARBBEIEMAQyBDA-'                                     
union select '+BBMEQAQwBFIEMAQ9BEEEOgQ+- +BDIEMARBBD8EOARCBDAEWgQ1-'  	                             
union select '+BCEEQAQ/BEEEOgQ4- +BFgENQQ3BDgEOg- +BDg- +BDoEWgQ4BDYENQQyBD0EPgRBBEI-'                          
union select '+BBUEPQQzBDsENQRBBDoEOA- +BFgENQQ3BDgEOg-'                                     
union select '+BCEEPgRGBDgEPgQ7BD4EMwQ4BFgEMA-'                                        
union select '+BCQEOAQ3BDgERwQ6BD4- +BDIEMARBBD8EOARCBDAEWgQ1-'                                  
union select '+BBwEMARCBDUEPAQwBEIEOAQ6BDA-'                                         
union select '+BB4EQQQ9BD4EMgQ4- +BDUEOgQ+BD0EPgQ8BDgEWAQ1-'                                  
union select '+BBAEQAQwBD0ENgQ4BEAEMARaBDU- +BEM- +BEIEQAQzBD4EMgQ4BD0EOA-'                              
union select '+BCYEQARCBDAEWgQ1- +BDg- +BD4EMQQ7BDgEOgQ+BDIEMARaBDU-'                                
union select '+BB8ENQRABEEEPwQ1BDoEQgQ4BDIEMA-'                                        
union select '+BCQEPgRCBD4EMwRABDAERAQ4BFgEMA- +BEEEMA- +BDMEQAQwBEQEOARHBDoEOAQ8- +BEIENQRFBD0EOAQ6BDAEPAQw-'                 
union select '+BCQEPgRABDwEMA- +BDg- +BD4EMQQ7BDgEOgQ+BDIEMARaBDU-'                                 
union select '+BBIENQRABEEEOgQw- +BD0EMARBBEIEMAQyBDA-'                                     
union select '+BBMEQAQwBFIEMAQ9BEEEOgQ+- +BDIEMARBBD8EOARCBDAEWgQ1-'                                
union select '+BCEEQAQ/BEEEOgQ4- +BFgENQQ3BDgEOg- +BDg- +BDoEWgQ4BDYENQQyBD0EPgRBBEI-'                          
union select '+BBUEPQQzBDsENQRBBDoEOA-  +BFgENQQ3BDgEOg-'                                    
union select '+BCQEOAQ7BD4ENwQ+BEQEOARYBDA-'                                         
union select '+BCQEOAQ3BDgERwQ6BD4- +BDIEMARBBD8EOARCBDAEWgQ1-'                                  
union select '+BBwEMARCBDUEPAQwBEIEOAQ6BDA-'                                         
union select '+BCMEQQRCBDAEMg- +BDg- +BD8EQAQwBDIEMA- +BDMEQAQwBFIEMAQ9BDA-'                              
union select '+BB0EMARGBDgEPgQ9BDAEOwQ9BDA- +BDUEOgQ+BD0EPgQ8BDgEWAQw-'                               
union select '+BBwEMARABDoENQRCBDgEPQQz-'                                          
union select '+BBAEQAQwBD0ENgQ4BEAEMARaBDU- +BEM- +BEIEQAQzBD4EMgQ4BD0EOA-'                              
union select '+BCYEQARCBDAEWgQ1- +BDg- +BD4EMQQ7BDgEOgQ+BDIEMARaBDU-'                                
union select '+BB8EQAQ+BFgENQQ6BEIEPgQyBDAEWgQ1-'                                       
union select '+BB8EQQQ4BEUEPgQ7BD4EMwQ4BFgEMA-'                                        
union select '+BBIENQRABEEEOgQw- +BD0EMARBBEIEMAQyBDA-'                                     
union select '+BBMEQAQwBFIEMAQ9BEEEOgQ+- +BDIEMARBBD8EOARCBDAEWgQ1-'      
union select '+BB4EQQQ9BD4EMgQ4- +BDUEOgQ+BD0EPgQ8BDgEOgQ1- +BEIEQAQzBD4EMgQ4BD0ENQ-'
union select '+BCIEQAQzBD4EMgQ4BD0EQQQ6BD4- +BD8EPgRBBDsEPgQyBDAEWgQ1-'
union select '+BBUEOgQ+BD0EPgQ8BDgEOgQw- +BDg- +BD4EQAQzBDAEPQQ4BDcEMARGBDgEWAQw- +BEIEQAQzBD4EMgQ4BD0EQQQ6BDgERQ- +BD8EQAQ1BDQEQwQ3BDUEWwQw-'
union select '+BB8EPgRBBDsEPgQyBD0EMA- +BDgEPQREBD4EQAQ8BDAEQgQ4BDoEMA-'
union select '+BCIEQAQzBD4EMgQ4BD0EQQQ6BD4- +BD8EPgRBBDsEPgQyBDAEWgQ1-'
union select '+BB8EQAQwBDoEQgQ4BEcEPQQw- +BD0EMARBBEIEMAQyBDA-'
union select '+BB4EQQQ9BD4EMgQ4- +BDUEOgQ+BD0EPgQ8BDgEWAQ1-'
union select '+BCAEMARHBEMEPQQ+BDIEPgQ0BEEEQgQyBD4-'
union select '+BB8EPgQ3BD0EMAQyBDAEWgQ1- +BEAEPgQxBDU-'
union select '+BB8EQQQ4BEUEPgQ7BD4EMwQ4BFgEMA-'
union select '+BCQEOAQ7BD4ENwQ+BEQEOARYBDA-'
union select '+BCMEQQRCBDAEMg- +BDg- +BD8EQAQwBDIEMA- +BDMEQAQwBFIEMAQ9BDA-'
union select '+BB0EMARGBDgEPgQ9BDAEOwQ9BDA- +BDUEOgQ+BD0EPgQ8BDgEWAQw-'
union select '+BBwEMARABDoENQRCBDgEPQQz-'
union select '+BB8EQAQwBDIEPg-'
union select '+BCAEMARHBEMEPQQ+BDIEPgQ0BEEEQgQyBD4-'
union select '+BB8EPgQ3BD0EMAQyBDAEWgQ1- +BEAEPgQxBDU-'
union select '+BB0ENQQ8BDAERwQ6BDg-  +BFgENQQ3BDgEOg-'
union select '+BB8EQAQ4BD0ERgQ4BD8EOA- +BDUEOgQ+BD0EPgQ8BDgEWAQ1-'
union select '+BB8EQAQwBDIEPg-'
union select '+BBoEMAQ9BEYENQQ7BDAEQAQ4BFgEQQQ6BD4- +BD8EPgRBBDsEPgQyBDAEWgQ1-'
union select '+BCAEMARHBEMEPQQ+BDIEPgQ0BEEEQgQyBD4- +BEM- +BEIEQAQzBD4EMgQ4BD0EOA-'
union select '+BB4EQAQzBDAEPQQ4BDcEMARGBDgEWAQw- +BD0EMAQxBDAEMgQ6BDU- +BDg- +BD8EQAQ+BDQEMARYBDU-'
union select '+BB4EMQRDBDoEMA- +BEM- +BDIEOARABEIEQwQ1BDsEPQQ+BDw- +BD8EQAQ1BDQEQwQ3BDUEWwRD-'
union select '+BB8EPgRBBDsEPgQyBD0EMA- +BDgEPQREBD4EQAQ8BDAEQgQ4BDoEMA-'
union select '+BBwENQRSBEMEPQQwBEAEPgQ0BD0EMA- +BEgEPwQ1BDQEOARGBDgEWAQw-'
union select '+BCEEQgQwBEIEOARBBEIEOAQ6BDA-'
union select '+BBwEQwQ3BDgERwQ6BDA- +BDoEQwQ7BEIEQwRABDA-'
union select '+BBUEOgQ+BDsEPgQzBDgEWAQw- +BDg- +BDcEMARIBEIEOARCBDA- +BDYEOAQyBD4EQgQ9BDU- +BEEEQAQ1BDQEOAQ9BDU-'
union select '+BBgEQQRCBD4EQAQ4BFgEMA- (+BD4ENAQwBDEEQAQwBD0ENQ- +BEIENQQ8BDU-)'
union select '+BBgENwQwBDEEQAQwBD0EMA- +BD8EPgQzBDsEMAQyBFkEMA- +BDwEMARCBDUEPAQwBEIEOAQ6BDU-'
union select '+BBsEPgQzBDgEOgQw- +BEEEMA- +BDUEQgQ4BDoEPgQ8-'
union select '+BBoEPgQ8BDUEQARGBDgEWAQwBDsEPQQ+- +BD8EPgQ3BD0EMAQyBDAEWgQ1- +BEAEPgQxBDU-'
union select '+BBIENQRIBEIEOAQ9BDU- +BDoEPgQ8BEMEPQQ4BDoEMARGBDgEWAQ1-'
union select '+BB8EPgRBBDsEPgQyBD0EMA- +BDUEOgQ+BD0EPgQ8BDgEWAQw-'
union select '+BCEEPgRGBDgEPgQ7BD4EMwQ4BFgEMA- +BEEEMA- +BD8EQAQwBDIEOAQ8BDA- +BDMEQAQwBFIEMAQ9BDA-'
union select '+BBwEMARABDoENQRCBDgEPQQz- +BEM- +BEIEQAQzBD4EMgQ4BD0EOA-'
union select '+BCQEOAQ9BDAEPQRBBDgEWAQ1-'
union select '+BB8EQAQ1BDQEQwQ3BDUEQgQ9BDgESARCBDIEPg-'
union select '+BB8EPgRBBDsEPgQyBD0EOA- +BEEEQgRABDAEPQQ4- +BFgENQQ3BDgEOg-'
union select '+BBwENQQ9BDAEXwQ8BDUEPQRC-'
union select '+BBUEOwQ1BDoEQgRABD4EPQRBBDoEPg- +BD8EPgRBBDsEPgQyBDAEWgQ1-'
union select '+BCEEPwQ+BFkEPQQ+BEIEQAQzBD4EMgQ4BD0EQQQ6BD4- +BD8EPgRBBDsEPgQyBDAEWgQ1-'
union select '+BBsEPgQzBDgEOgQw-'
union select '+BB8EPgRBBDsEPgQyBD0ENQ- +BEQEOAQ9BDAEPQRBBDgEWAQ1-'
union select '+BB4EQQQ9BD4EMgQ4- +BEIEQAQzBD4EMgQ4BD0ENQ-'
union select '+BCIENQRFBD0EOAQ6BDA- +BD8EQAQ+BDQEMARYBDU- +BDg- +BEMEQQQ7BEMEMwQ1- +BDoEQwQ/BEYEOAQ8BDA-'
union select '+BB8EPgRBBDsEPgQyBD0EMA- +BDoEPgQ8BEMEPQQ4BDoEMARGBDgEWAQw-'
union select '+BB8EPgQ3BD0EMAQyBDAEWgQ1- +BEAEPgQxBDU-'
union select '+BB4EQQQ9BD4EMgQ4- +BD8EPgRBBDsEPgQyBDAEWgQw- +BEM- +BEIEQAQzBD4EMgQ4BD0EOA-'
union select '+BBwEMARABDoENQRCBDgEPQQz- +BEM- +BEIEQAQzBD4EMgQ4BD0EOA-'
union select '+BB0EMAQxBDAEMgQ6BDA- +BDg- +BEQEOAQ3BDgERwQ6BDA- +BDQEOARBBEIEQAQ4BDEEQwRGBDgEWAQw-'
union select '+BB8EQQQ4BEUEPgQ7BD4EMwQ4BFgEMA- +BD8EPgRCBEAEPgRIBDAERwQw-'
union select '+BBwEQwQ3BDgERwQ6BDA- +BDoEQwQ7BEIEQwRABDA-'
union select '+BCEEQgRABDAEPQQ4- +BFgENQQ3BDgEOg- 1'                              
) a
)b


select +ACo- from Predmet 