//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Smer()
        {
            this.SmerGodinas = new HashSet<SmerGodina>();
        }
    
        public int Id { get; set; }
        public string naziv { get; set; }
        public string stecenoZvanje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmerGodina> SmerGodinas { get; set; }
    }
}
