//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentum
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmerGodinaPredmet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SmerGodinaPredmet()
        {
            this.UcenikOcenas = new HashSet<UcenikOcena>();
        }
    
        public int Id { get; set; }
        public Nullable<int> smerGodinaId { get; set; }
        public Nullable<int> predmetId { get; set; }
        public Nullable<int> grupaId { get; set; }
        public Nullable<byte> uticeNaUspeh { get; set; }
        public Nullable<int> redniBroj { get; set; }
    
        public virtual Grupa Grupa { get; set; }
        public virtual Predmet Predmet { get; set; }
        public virtual SmerGodina SmerGodina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcenikOcena> UcenikOcenas { get; set; }
    }
}
