//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentum
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmerGodina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SmerGodina()
        {
            this.Razreds = new HashSet<Razred>();
            this.SmerGodinaDokuments = new HashSet<SmerGodinaDokument>();
            this.SmerGodinaPredmets = new HashSet<SmerGodinaPredmet>();
        }
    
        public int Id { get; set; }
        public Nullable<int> smerId { get; set; }
        public Nullable<int> godina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Razred> Razreds { get; set; }
        public virtual Smer Smer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmerGodinaDokument> SmerGodinaDokuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmerGodinaPredmet> SmerGodinaPredmets { get; set; }
    }
}
