//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentum
{
    using System;
    using System.Collections.Generic;
    
    public partial class UcenikBookmark
    {
        public int Id { get; set; }
        public Nullable<int> bookmarkId { get; set; }
        public string value { get; set; }
        public Nullable<int> ucenikDokumentId { get; set; }
    
        public virtual Bookmark Bookmark { get; set; }
        public virtual UcenikDokument UcenikDokument { get; set; }
    }
}
