//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentum
{
    using System;
    using System.Collections.Generic;
    
    public partial class UcenikOcena
    {
        public int Id { get; set; }
        public Nullable<int> ucenikId { get; set; }
        public Nullable<int> ocena { get; set; }
        public Nullable<int> smerGodinaPredmetId { get; set; }
        public string ocenaOpis { get; set; }
    
        public virtual Ucenik Ucenik { get; set; }
        public virtual SmerGodinaPredmet SmerGodinaPredmet { get; set; }
    }
}
