//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucenik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ucenik()
        {
            this.UcenikDokuments = new HashSet<UcenikDokument>();
            this.UcenikGrupas = new HashSet<UcenikGrupa>();
            this.UcenikOcenas = new HashSet<UcenikOcena>();
        }
    
        public int Id { get; set; }
        public Nullable<int> razredId { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public Nullable<System.DateTime> datum_rodjenja { get; set; }
        public Nullable<int> redniBroj { get; set; }
        public string brojMaticneKnjige { get; set; }
        public string imeRoditelja { get; set; }
        public string mestoRodjenja { get; set; }
        public string delovodniBroj { get; set; }
        public string kojiput { get; set; }
        public string opstina { get; set; }
        public string drzava { get; set; }
    
        public virtual Razred Razred { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcenikDokument> UcenikDokuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcenikGrupa> UcenikGrupas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcenikOcena> UcenikOcenas { get; set; }
    }
}
